// @generated by buffa-codegen. DO NOT EDIT.
// source: future.proto

/// Future schema used to check old-reader round trips without losing new fields.
#[derive(Clone, PartialEq, Default)]
pub struct FutureControl {
    /// Field 1: `operation`
    pub operation: u32,
    /// Field 2: `request_id`
    pub request_id: u64,
    /// Field 100: `optional_trace`
    pub optional_trace: ::buffa::alloc::string::String,
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for FutureControl {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("FutureControl")
            .field("operation", &self.operation)
            .field("request_id", &self.request_id)
            .field("optional_trace", &self.optional_trace)
            .finish()
    }
}
impl FutureControl {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/fixture.future.FutureControl";
}
::buffa::impl_default_instance!(FutureControl);
impl ::buffa::MessageName for FutureControl {
    const PACKAGE: &'static str = "fixture.future";
    const NAME: &'static str = "FutureControl";
    const FULL_NAME: &'static str = "fixture.future.FutureControl";
    const TYPE_URL: &'static str = "type.googleapis.com/fixture.future.FutureControl";
}
impl ::buffa::Message for FutureControl {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.operation != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.operation) as u64;
        }
        if self.request_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.request_id) as u64;
        }
        if !self.optional_trace.is_empty() {
            size
                += 2u64
                    + ::buffa::types::string_encoded_len(&self.optional_trace) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.operation != 0u32 {
            ::buffa::types::put_uint32_field(1u32, self.operation, buf);
        }
        if self.request_id != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.request_id, buf);
        }
        if !self.optional_trace.is_empty() {
            ::buffa::types::put_string_field(100u32, &self.optional_trace, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.operation = ::buffa::types::decode_uint32(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.request_id = ::buffa::types::decode_uint64(buf)?;
            }
            100u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.optional_trace, buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.operation = 0u32;
        self.request_id = 0u64;
        self.optional_trace.clear();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for FutureControl {
    const PROTO_FQN: &'static str = "fixture.future.FutureControl";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
